apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
  labels:
    app: {{ template "fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
data:
  config.ts: |
    export var APIURL = "http://{{ .Values.api.domain }}.{{ .Values.basedomain }}";